### ISSUE TITLE
bash errors: shopt:globstar and unexpected EOF

### ISSUE THREAD

**Issue by beekman** [mhulse/dotfizzles#120]
These errors popped up recently in my terminal. Any ideas?

-bash: shopt: globstar: invalid shell option name
-bash: eval: line 48: syntax error: unexpected end of file

**Comment by beekman** [comment]
Line 46 of common.bash is responsible for the shopt:globstar warning.
shopt -s globstar

Any ideas why recursive globbing is causing me problems?

**Comment by mhulse** [comment]
Hey! I think this will fix it:

* [Upgrade bash on OS X](https://github.com/mhulse/dotfizzles/wiki/Upgrade-bash-on-OS-X)

I've been meaning to put a note about bash 4 upgrade in the README: #98 

Let me know if that doesn't work. 👍

**Comment by beekman** [comment]
That did the trick! Thanks Micky!

**Comment by mhulse** [comment]
Sure thing! Glad it helped. :octocat:
