### ISSUE TITLE
Bash 4.x

### ISSUE THREAD

**Issue by mhulse** [mhulse/dotfizzles#98]
https://github.com/mhulse/dotfizzles/wiki/Upgrade-bash-on-OS-X

Put those instructions in README

**Comment by beekman** [comment]
So, I installed your dotfizzles on another Mac, and though I didn't get the unexpected EOF error, globbing wasn't working, even after I installed and upgraded bash via homebrew and restarted. The last few steps in these instructions were the missing pieces, at least for me:

> Check if you can enable `glob` support, run this command.
> 
> ```
> shopt -s globstar
> ```
> 
> If nothing happens you're good to glob. If you get an error that looks something like this, proceed to the next section.
> ```
> bash: shopt: globstar: invalid shell option name
> ```
> 
> ### Updating `bash`
> 
> Check to see what version of bash you're running
> ```
> bash --version
> ```
> 
> Install bash:
> 
> ```
> brew update && brew install bash
> ```
> 
> Append the `/etc/shells` file with the new shell path:
> 
> ```
> sudo bash -c 'echo /usr/local/bin/bash >> /etc/shells'
> ```
> 
> Then change to the new shell:
> 
> ```
> chsh -s /usr/local/bin/bash 
> ```
> 
> Now you have to quit the terminal and open it back up again. If you check the version it should show something updated.
> 
> ```
> bash --version
> ```
> 
> To enable `glob` support run the following.
> 
> ```
> shopt -s globstar

**Comment by mhulse** [comment]
Ahhhh, good catch! Looks like it was the `sudo bash -c ...` and `chsh` stuff?

I'll be sure to clarify the docs. I have several issues relating to README docs/instructions, so I'll be sure to clarify this when I do an update (hopefully this weekend).

Thanks for the feedback and report. It can be hard to account for some of the new install stuff when I've been using this for a while (it's easy to miss the fresh install stuff).

👍

**Comment by mhulse** [comment]
Adding all doc issues to the [README](https://github.com/mhulse/dotfizzles/labels/README) label.

**Comment by mhulse** [comment]
Added note about upgrading to bash4 in wiki:

https://github.com/mhulse/dotfizzles/wiki/Optional-dependencies

Closing.
